### ISSUE TITLE
GraphicsEngine setting cannot be saved

### ISSUE THREAD

**Issue by faulgurke** [jugstalt/gview-gis#12]
Version 5.22.4601: Changing GraphicsEngine in MapProperties -> Map/Display ->AdvancedTools -> GraphicsEngine from "SkiaSharp" to "GdiPlus" cannot be saved.
When saving and reopening the GraphicsEngine is reset to "SkiaSharp" which has undesirable effects on labelling.

**Comment by jugstalt** [comment]
Die GraphicsEngine wird nicht im Projekt mitgespeichert. Das ist Absicht.
Grundsätzlich sollte Skia verwendet werden. Darum ist das auch der Standard.

Für den Server kann man die Rendering Engine global über die Settings einstellen.
Die Möglichkeit des des Umstellens im gView.Carto dient nur dazu, die Darstellung für bestimmte Server Instanzen zu testen.
