### ISSUE TITLE
Darstellungsdifferenzen bei Verwendung unterschiedlicher rendering-engines

### ISSUE THREAD

**Issue by faulgurke** [jugstalt/gview-gis#13]
Die "neue" rendering-engine "skiasharp" liefert (im Vergleich zur "alten" engine "gdiplus") übereinandergeschobene Labels.
Siehe Screenshots.
gdiplus - so soll es aussehen
![label1_gp](https://user-images.githubusercontent.com/100088983/213151256-d927ac32-d75a-40f6-8ced-137ff8a0dc65.png)
skiasharp - Buchstaben leicht übereinandergeschoben
![label1_ss](https://user-images.githubusercontent.com/100088983/213151260-c3cb474f-740c-4dc7-b694-ca05ca400439.png)
gdiplus
![label2_gp](https://user-images.githubusercontent.com/100088983/213151261-62677426-3ff2-46e6-8910-bc9846abacf9.png)
skiasharp
![label2_ss](https://user-images.githubusercontent.com/100088983/213151263-68c007c9-3a1d-4f12-96b5-672b34f0185a.png)

**Comment by jugstalt** [comment]
Die Darstellung wurde für Skia verbessert. 
Die Änderung sind im nächsten Release 5.23.x mit dabei.
