### ISSUE TITLE
Line Labelling Orientation - Label not drawn perpendicular

### ISSUE THREAD

**Issue by faulgurke** [jugstalt/gview-gis#15]
I defined Line Labelling Orientation as perpendiclular. But the label will not be drawn perpendicluar to the line but in an upright position.
Any suggestions?
![label_perpen](https://user-images.githubusercontent.com/100088983/228538707-2267486a-05d4-4d0a-8cf3-e7e532e573c0.png)
![label_is](https://user-images.githubusercontent.com/100088983/228538727-9cf96919-00ff-4a8a-af11-4355622cdd2c.png)

**Comment by jugstalt** [comment]
works with the current version as it should. Is the problem still there?
