### ISSUE TITLE
Server on Linux

### ISSUE THREAD

**Issue by charga** [jugstalt/gview-gis#20]
I'd tried to publish gView.Server on a Linux machine, when run it show some errors of some local path attached to windows. I found mapserver.json on the source and saw those path. Do I need to change to local linux paths? What other think need to change?

Thanks

**Comment by jugstalt** [comment]
There is a linux container you can run on docker or kubernetes. Maybe this works for you:

https://hub.docker.com/r/gstalt/gview5-server

You can inspect the docker image to see how the mapserver.json should look like on linux

A template for this file is this:

``` javascript
{
  "services-folder": "{installation-path}/server-files/configuration",
  "output-path": "{installation-path}/server-files/web/output",
  "output-url": "{installation-host}/output",
  "onlineresource-url": "{installation-host}",
  "tilecache-root": "{installation-path}/server-files/web/tile-caches",

  "task-queue": {
    "max-parallel-tasks": 10,
    "max-queue-length": 1000
  },

  "allowFormsLogin": true,
  "force-https":  false,
  
    "graphics": {
    "rendering": "skia",
    "encoding": "skia"
  },
}
```
