### ISSUE TITLE
version 6

### ISSUE THREAD

**Issue by charga** [jugstalt/gview-gis#27]
Hi, I update the code with the 6 branch, and notice many changes:
The new main entry is gView.WebApps instead of gView.Web, but also ask for a user/password login..

Wich are this user?
There is a config file with admin and carto user, but hashed passwords

How can I login?

Thanks in advance

**Comment by gis-eni** [comment]
Hi, the Password in the config is SHA256 or SH512 encoded.
Try "password" ;)
The documentation will follow in the next few days.

**Comment by charga** [comment]
Ok, perfect. Explorer works, Server works, but Carto never start.Something missing?

**Comment by jugstalt** [comment]
Maybe. There are not all the binary dependencies in the repo. Thridpardy dlls are only in the release installation package.
If you compile everything by yourself, you must copy this dependencies to the bin/.../debug/net8/ folder. 

I guess, the most missing dependencies are the ``proj.dll`` and ``proj.db`` (proj4). 
You can try to copy them from the old gview4 release.

**Comment by charga** [comment]
great
