### ISSUE TITLE
Labelling in gView 

### ISSUE THREAD

**Issue by marko-jer** [jugstalt/gview-gis#31]
In gview regardless of which version (5 or 6) the labelling for certain polygons (Kataster Grundstück) does not work. 
As far as I have been able to observe, it mainly affects small polygons - smaller than 30 square metres, but not all. 
e.g. In the Digitaler Atlas  you can search for properties by size
![image](https://github.com/jugstalt/gview-gis/assets/1842500/0fabc271-c85c-49ac-90eb-3f1bfd9f50ae)
in the Basiskarte. 
Do you need more information?
Do you have any idea why this is happening?

**Comment by marko-jer** [comment]
Further note:
if a vertex or part of the object is outside the visible area, the labelling is displayed - both in gView and in Digitaler Atlas.
| _ | Digitaler Atlas | gView |
| --- | --- | --- |
|without labeling|![image](https://github.com/jugstalt/gview-gis/assets/1842500/ff01984b-71cb-4cf4-bdd8-a670ca0d241a)|![image](https://github.com/jugstalt/gview-gis/assets/1842500/c9ba2116-7d87-4330-b670-9bb1f6f66236)|
|with labeling|![image](https://github.com/jugstalt/gview-gis/assets/1842500/f15c56e3-3eda-4454-b5ec-5254b20b13ca)|![image](https://github.com/jugstalt/gview-gis/assets/1842500/9c08d775-4424-41b8-9d81-d2a091e9da7d)|

**Comment by gis-eni** [comment]
Fixed in current Build
