### ISSUE TITLE
New Functionalities

### ISSUE THREAD

**Issue by 11wecht** [jugstalt/gview-gis#34]
We would like to propose the implementation of several new functionalities to enhance our current system.

Proposed Features:

    Clone Layer:
        Implement functionality to clone existing layers within the project.

    Import Renderer & Properties:
        Enable users to import renderer configurations and associated properties from external sources.

    Split with Filter:
        Add a feature that allows users to split data with specific filters applied for better data management.

**Comment by jugstalt** [comment]
all done...
