### ISSUE TITLE
How to use Network

### ISSUE THREAD

**Issue by giszh86** [jugstalt/gview-gis#8]
When I add data from postgis to the map,the Network Tool can not visible, why that happend, how to use it, thanks a lot.
![image](https://user-images.githubusercontent.com/8955999/126746096-dabae732-9a55-4c3a-8484-ad8fad28025b.png)
![image](https://user-images.githubusercontent.com/8955999/126746427-44375a52-0a8f-4758-8b8c-f4c3f80f3200.png)

**Comment by jugstalt** [comment]
Sorry for my late response, i very busy ;) hope you are still interested in gView GIS.

I developed the first version of gView GIS a long time ago (>20 years). There was also a network support but not for Networks with PostGIS.

Now, with gView 5 the focus of the software is not the desktop viewer (gView.Carto).
If you need an opensource desktop GIS i recommend QGIS.

gView.Carto now is "only" an map authoring program. You can create maps with nice cartography and publish this maps to the gView Server to publich high performant dyanmic Web Services (GeoServices REST, WMS, ...)
